#define NS_PRIVATE_IMPLEMENTATION
#define AK_PRIVATE_IMPLEMENTATION
#define CA_PRIVATE_IMPLEMENTATION
#define MTL_PRIVATE_IMPLEMENTATION
#define MDL_PRIVATE_IMPLEMENTATION
#define MTK_PRIVATE_IMPLEMENTATION

#include "MetalKit/MetalKit.hpp"

int main()
{
    return 0;
}
